### ISSUE TITLE
Error when running get_data.py

### ISSUE THREAD

**Issue by kalilfagundes** [saifalisew1508/TelegramAdderTool#9]
Choose Method Username or ID: ID
Traceback (most recent call last):
File "C:\Users\xxxx\Documents\TelegramAdder\TelegramAdderTool-main\get_data.py", line 31, in
asyncio.run(main())
File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "C:\Users\xx\Documents\TelegramAdder\TelegramAdderTool-main\get_data.py", line 27, in main
await get_data(gp_s_id, gp_t_id, config, method)
File "C:\Users\xx\Documents\TelegramAdder\TelegramAdderTool-main\helper\data.py", line 21, in get_data
async with Client(phone, workdir="session") as app:
File "C:\Python312\Lib\site-packages\pyrogram\client.py", line 311, in aenter
return await self.start()
^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
is_authorized = await self.connect()
^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
await self.load_session()
File "C:\Python312\Lib\site-packages\pyrogram\client.py", line 616, in load_session
await self.storage.open()
File "C:\Python312\Lib\site-packages\pyrogram\storage\file_storage.py", line 63, in open
self.update()
File "C:\Python312\Lib\site-packages\pyrogram\storage\file_storage.py", line 38, in update
version = self.version()
^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 214, in version
return self.conn.execute(
^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: number

**Comment by kalilfagundes** [comment]
Choose Method Username or ID: ID
Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\TelegramAdder\TelegramAdderTool-main\get_data.py", line 31, in <module>
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xx\Documents\TelegramAdder\TelegramAdderTool-main\get_data.py", line 27, in main
    await get_data(gp_s_id, gp_t_id, config, method)
  File "C:\Users\xx\Documents\TelegramAdder\TelegramAdderTool-main\helper\data.py", line 21, in get_data
    async with Client(phone, workdir="session") as app:
  File "C:\Python312\Lib\site-packages\pyrogram\client.py", line 311, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Python312\Lib\site-packages\pyrogram\client.py", line 616, in load_session
    await self.storage.open()
  File "C:\Python312\Lib\site-packages\pyrogram\storage\file_storage.py", line 63, in open
    self.update()
  File "C:\Python312\Lib\site-packages\pyrogram\storage\file_storage.py", line 38, in update
    version = self.version()
              ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 214, in version
    return self.conn.execute(
           ^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: number
